#!/usr/bin/env python3
from __future__ import annotations
import argparse
import json
from pathlib import Path

from hall_pair_relations import audit_type_a, verify_a4_ordered_exchange


def build_certificate() -> dict:
    ranks = [audit_type_a(n) for n in range(2, 7)]
    a4 = next(x for x in ranks if x["rank"] == 4)
    return {
        "status": "PASS",
        "scope": "type A_2 through A_6 polygon and universal Hall/BZ pair identities",
        "ranks": ranks,
        "totals": {
            key: sum(x[key] for x in ranks)
            for key in (
                "diagonals", "crossing_pairs", "compatible_pairs",
                "triangulations", "exchange_pair_witnesses",
                "common_cluster_witnesses", "symbolic_local_identity_checks",
            )
        },
        "A4": {
            **a4,
            "ordered_exchange": verify_a4_ordered_exchange(),
            "distinguished_relation": "XY-v^(-2)YX=(1-v^(-2))X2",
            "nonrigid_split_value": "Phi(epsilon_{X direct_sum Y})=YX=X2+v*X3",
        },
        "audit_boundary": (
            "The program proves exact symbolic normalization identities and polygon "
            "flip/compatibility combinatorics. It does not enumerate arbitrary finite-field "
            "Hall numbers; those enter the paper through Riedtmann--Peng and the PBW proof."
        ),
    }


def write_tex(data: dict, path: Path) -> None:
    a4 = data["A4"]
    t = data["totals"]
    lines = [
        "% generated by verify_whole_hall_typeA.py",
        rf"\newcommand{{\CertAIVDiagonals}}{{{a4['diagonals']}}}",
        rf"\newcommand{{\CertAIVCrossings}}{{{a4['crossing_pairs']}}}",
        rf"\newcommand{{\CertAIVClusters}}{{{a4['triangulations']}}}",
        rf"\newcommand{{\CertTotalDiagonals}}{{{t['diagonals']}}}",
        rf"\newcommand{{\CertTotalCrossings}}{{{t['crossing_pairs']}}}",
        rf"\newcommand{{\CertTotalClusters}}{{{t['triangulations']}}}",
        rf"\newcommand{{\CertLocalChecks}}{{{t['symbolic_local_identity_checks']}}}",
        rf"\newcommand{{\CertExchangeWitnesses}}{{{t['exchange_pair_witnesses']}}}",
        rf"\newcommand{{\CertCompatibleWitnesses}}{{{t['common_cluster_witnesses']}}}",
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--json", type=Path, default=Path("generated/whole_hall_typeA_certificate.json"))
    p.add_argument("--tex", type=Path, default=Path("generated/whole_hall_typeA_results.tex"))
    args = p.parse_args()
    data = build_certificate()
    args.json.parent.mkdir(parents=True, exist_ok=True)
    args.json.write_text(json.dumps(data, indent=2, sort_keys=True), encoding="utf-8")
    write_tex(data, args.tex)
    print("Whole-Hall type-A certificate: PASS")
    for x in data["ranks"]:
        print(f"  A{x['rank']}: diagonals={x['diagonals']}, crossings={x['crossing_pairs']}, clusters={x['triangulations']}, pair identities={x['symbolic_local_identity_checks']}")
    print("  A4 q-commutator:", data["A4"]["distinguished_relation"])
    print("  JSON:", args.json)
    print("  TeX macros:", args.tex)

if __name__ == "__main__":
    main()
