#!/usr/bin/env python3
"""Deterministic classical type-A4 polygon Hall--skein certificate."""

from __future__ import annotations

import argparse
import json
from pathlib import Path

from hall_skein import audit_polygon, all_diagonals, crossing_pairs, resolve


def build_certificate() -> dict:
    # Cluster type A4 is the heptagon model.
    audit = audit_polygon(7)
    diagonals = all_diagonals(7)

    # Record a representative incompatible pair and its Ptolemy expansion.
    sample = ((0, 3), (1, 5))
    sample_expansion = {
        str(curve): str(coefficient)
        for curve, coefficient in resolve(sample, 7).items()
    }

    return {
        "status": "PASS",
        "specialization": "classical Ptolemy straightening at omega=1",
        "model": "cluster type A4 as a convex heptagon",
        "vertices": audit.vertices,
        "diagonals": audit.diagonals,
        "crossing_pairs": audit.crossing_pairs,
        "triangulations": audit.triangulations,
        "triple_associativity_checks": audit.triple_associativity_checks,
        "first_crossing_confluence_checks": audit.confluence_checks,
        "degree_four_multicurves": audit.degree_four_curves,
        "sample_crossing": [list(a) for a in sample],
        "sample_crossing_count": len(crossing_pairs(sample, 7)),
        "sample_expansion": sample_expansion,
        "diagonal_list": [list(a) for a in diagonals],
        "scope_note": (
            "The certificate audits polygon counts and classical Ptolemy "
            "straightening at omega=1.  Quantum endpoint-state and wall "
            "confluence are imported from the stated/walled skein theorems.  "
            "The certificate is not a substitute for the Hall filtration and "
            "quotient proof in the paper."
        ),
    }


def write_tex(data: dict, path: Path) -> None:
    lines = [
        "% Generated by verify_A4_hall_skein.py; do not edit by hand.",
        rf"\newcommand{{\AIVDiagonals}}{{{data['diagonals']}}}",
        rf"\newcommand{{\AIVCrossingPairs}}{{{data['crossing_pairs']}}}",
        rf"\newcommand{{\AIVTriangulations}}{{{data['triangulations']}}}",
        rf"\newcommand{{\AIVTripleChecks}}{{{data['triple_associativity_checks']}}}",
        rf"\newcommand{{\AIVConfluenceChecks}}{{{data['first_crossing_confluence_checks']}}}",
        rf"\newcommand{{\AIVAssociativityChecks}}{{{data['triple_associativity_checks']}}}",
        rf"\newcommand{{\AIVDegreeFourCurves}}{{{data['degree_four_multicurves']}}}",
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--json", type=Path, default=Path("generated/A4_hall_skein_certificate.json"))
    parser.add_argument("--tex", type=Path, default=Path("generated/A4_hall_skein_results.tex"))
    args = parser.parse_args()

    data = build_certificate()
    args.json.parent.mkdir(parents=True, exist_ok=True)
    args.json.write_text(json.dumps(data, indent=2, sort_keys=True), encoding="utf-8")
    write_tex(data, args.tex)

    print("A4 classical Hall--skein certificate: PASS")
    print(f"  diagonals: {data['diagonals']}")
    print(f"  crossing pairs: {data['crossing_pairs']}")
    print(f"  triangulations: {data['triangulations']}")
    print(f"  triple associativity checks: {data['triple_associativity_checks']}")
    print(f"  first-crossing confluence checks: {data['first_crossing_confluence_checks']}")
    print(f"  JSON: {args.json}")
    print(f"  TeX macros: {args.tex}")


if __name__ == "__main__":
    main()
