#!/usr/bin/env python3
"""Cross-rank deterministic regression for polygon Hall--skein straightening."""

from __future__ import annotations

import argparse
import json
from itertools import product
from pathlib import Path

from hall_skein import (
    all_diagonals,
    assert_associative,
    assert_first_choice_confluence,
    curve_multisets,
    expected_polygon_counts,
    triangulations,
)


def audit_rank(rank: int) -> dict:
    m = rank + 3
    diagonals = all_diagonals(m)
    expected = expected_polygon_counts(m)
    tris = triangulations(m)
    if len(diagonals) != expected["diagonals"] or len(tris) != expected["triangulations"]:
        raise AssertionError(f"polygon counts failed in rank {rank}")

    # Exhaustive triples in smaller ranks; deterministic bounded prefix later.
    singleton = [(a,) for a in diagonals]
    triples = list(product(singleton, repeat=3))
    if len(triples) > 6000:
        triples = triples[:6000]
    for a, b, c in triples:
        assert_associative(a, b, c, m)

    degree_limit = 1800 if rank <= 4 else 800
    confluence = 0
    degree_four = 0
    for curve in curve_multisets(diagonals, 4):
        degree_four += 1
        confluence += assert_first_choice_confluence(curve, m)
        if degree_four >= degree_limit:
            break

    return {
        "rank": rank,
        "vertices": m,
        "diagonals": len(diagonals),
        "crossing_pairs": expected["crossing_pairs"],
        "triangulations": len(tris),
        "triple_associativity_checks": len(triples),
        "degree_four_curves_checked": degree_four,
        "first_crossing_confluence_checks": confluence,
    }


def build_certificate() -> dict:
    audits = [audit_rank(rank) for rank in range(2, 7)]
    totals = {
        key: sum(item[key] for item in audits)
        for key in (
            "diagonals",
            "crossing_pairs",
            "triangulations",
            "triple_associativity_checks",
            "degree_four_curves_checked",
            "first_crossing_confluence_checks",
        )
    }
    return {
        "status": "PASS",
        "ranks": audits,
        "totals": totals,
        "maximum_rank": 6,
        "polygon_count": len(audits),
        "scope_note": (
            "The regression verifies the polygon straightening combinatorics "
            "with exact symbolic Laurent coefficients.  General Hall-algebra "
            "claims are proved in the accompanying TeX paper."
        ),
    }


def write_tex(data: dict, path: Path) -> None:
    total = data["totals"]
    lines = [
        "% Generated by verify_typeA_hall_skein.py; do not edit by hand.",
        rf"\newcommand{{\TypeAMaxRank}}{{{data['maximum_rank']}}}",
        rf"\newcommand{{\TypeAPolygons}}{{{data['polygon_count']}}}",
        rf"\newcommand{{\TypeATotalDiagonals}}{{{total['diagonals']}}}",
        rf"\newcommand{{\TypeATotalCrossings}}{{{total['crossing_pairs']}}}",
        rf"\newcommand{{\TypeATotalTriangulations}}{{{total['triangulations']}}}",
        rf"\newcommand{{\TypeATotalConfluence}}{{{total['first_crossing_confluence_checks']}}}",
        "",
    ]
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--json", type=Path, default=Path("generated/typeA_hall_skein_certificate.json"))
    parser.add_argument("--tex", type=Path, default=Path("generated/typeA_hall_skein_results.tex"))
    args = parser.parse_args()

    data = build_certificate()
    args.json.parent.mkdir(parents=True, exist_ok=True)
    args.json.write_text(json.dumps(data, indent=2, sort_keys=True), encoding="utf-8")
    write_tex(data, args.tex)

    print("Type-A Hall--skein cross-rank regression: PASS")
    for item in data["ranks"]:
        print(
            f"  A{item['rank']}: diagonals={item['diagonals']}, "
            f"crossings={item['crossing_pairs']}, triangulations={item['triangulations']}, "
            f"triple checks={item['triple_associativity_checks']}"
        )
    print(f"  JSON: {args.json}")
    print(f"  TeX macros: {args.tex}")


if __name__ == "__main__":
    main()
